# Configuration DefectDojo - Automatisation de l'initialisation de la BDD pour plan Free
services:
  # 1. Le Cache (Render Key Value)
  - type: keyvalue
    name: dojo-redis
    plan: free
    region: oregon
    ipAllowList: []

  # 2. L'application Web DefectDojo
  - type: web
    name: defectdojo-web
    runtime: image
    plan: free
    region: oregon
    image:
      url: docker.io/defectdojo/defectdojo-django:latest
    # --- AJOUT DE LA COMMANDE DE DÉMARRAGE AUTOMATIQUE ---
    # Cette commande initialise la BDD si nécessaire, puis lance le serveur standard
    startCommand: python3 manage.py initialize && uwsgi --ini /app/wsgi/uwsgi.ini
    # -----------------------------------------------------
    envVars:
      - key: PORT
        value: "8080"
      - key: UWSGI_HTTP
        value: ":8080"
      - key: UWSGI_BUFFER_SIZE
        value: "32768"
      - key: DD_DATABASE_URL
        fromDatabase:
          name: dojo-db-v2
          property: connectionString
      - key: DD_REDIS_URL
        fromService:
          type: keyvalue
          name: dojo-redis
          property: connectionString
      - key: DD_SECRET_KEY
        generateValue: true
      - key: DD_DEBUG
        value: "false"
      - key: DD_ALLOWED_HOSTS
        value: "*"

# 3. La Base de Données PostgreSQL
databases:
  - name: dojo-db-v2
    postgresMajorVersion: '18'
    plan: free
    region: oregon
    ipAllowList: []