# Configuration DefectDojo alignée sur la même région avec les bons ports
services:
  # 1. Le Cache (Render Key Value)
  - type: keyvalue
    name: dojo-redis
    plan: free
    region: oregon # Fixé en Oregon
    ipAllowList: []

  # 2. L'application Web DefectDojo
  - type: web
    name: defectdojo-web
    runtime: image
    plan: free
    region: oregon # Fixé en Oregon
    port: 8080 # <--- INDISPENSABLE : Dit à Render d'écouter le port 8080 du conteneur
    image:
      url: docker.io/defectdojo/defectdojo-django:latest
    envVars:
      - key: DD_DATABASE_URL
        fromDatabase:
          name: dojo-db
          property: connectionString
      - key: DD_REDIS_URL
        fromService:
          type: keyvalue
          name: dojo-redis
          property: connectionString
      - key: DD_SECRET_KEY
        generateValue: true
      - key: DD_DEBUG
        value: "false"
      - key: DD_ALLOWED_HOSTS
        value: "*"

# 3. La Base de Données PostgreSQL
databases:
  - name: dojo-db
    postgresMajorVersion: '18'
    plan: free
    region: oregon # <--- Force la BDD à se recréer en Oregon à côté des autres
    ipAllowList: []